
export const categories = [
  { id: 1, name: "Vehicles", icon: "/jiji/car.png", totalItems: 40230, subcategories: [
      { id: 101, name: "Cars", icon: "🚙", count: 18450 },
      { id: 102, name: "Buses & Microbuses", icon: "🚌", count: 820 },
      { id: 103, name: "Trucks & Trailers", icon: "🚛", count: 640 },
      { id: 104, name: "Motorcycles & Scooters", icon: "🏍️", count: 3100 },
      { id: 105, name: "Heavy Equipment", icon: "🏗️", count: 540 },
      { id: 106, name: "Watercraft & Boats", icon: "🚤", count: 120 },
      { id: 107, name: "Vehicle Parts", icon: "🔧", count: 9800 },
      { id: 108, name: "Vehicle Accessories", icon: "🛞", count: 4500 },
      { id: 109, name: "Auto Repair Services", icon: "🧰", count: 1560 },
      { id: 110, name: "Vehicle Rentals", icon: "🔑", count: 700 },
  ]},
  { id: 2, name: "Property", icon: "/jiji/property.png", totalItems: 55290, subcategories: [
      { id: 201, name: "Houses & Apartments for Sale", icon: "🏡", count: 14500 },
      { id: 202, name: "Houses & Apartments for Rent", icon: "🏢", count: 18300 },
      { id: 203, name: "Land & Plots", icon: "🌍", count: 7600 },
      { id: 204, name: "Commercial Property", icon: "🏬", count: 4100 },
      { id: 205, name: "Short Let", icon: "🛏️", count: 3400 },
      { id: 206, name: "Event Centers", icon: "🎪", count: 890 },
      { id: 207, name: "Property Services", icon: "🧑‍🔧", count: 6500 },
  ]},
  { id: 3, name: "Phones & Tablets", icon: "/jiji/phones.png", totalItems: 58500, subcategories: [
      { id: 301, name: "Smartphones", icon: "📱", count: 32000 },
      { id: 302, name: "Tablets", icon: "📲", count: 5800 },
      { id: 303, name: "Smart Watches", icon: "⌚", count: 4100 },
      { id: 304, name: "Accessories", icon: "🔌", count: 16600 },
  ]},
  { id: 4, name: "Electronics", icon: "/jiji/electronics.png", totalItems: 68000, subcategories: [
      { id: 401, name: "TVs", icon: "📺", count: 12500 },
      { id: 402, name: "Audio & Music Equipment", icon: "🎧", count: 4200 },
      { id: 403, name: "Computer Hardware", icon: "🖥️", count: 14500 },
      { id: 404, name: "Computer Accessories", icon: "🖱️", count: 18000 },
      { id: 405, name: "Cameras", icon: "📷", count: 3100 },
      { id: 406, name: "Printers", icon: "🖨️", count: 1800 },
      { id: 407, name: "Networking Equipment", icon: "📡", count: 4200 },
      { id: 408, name: "Video Game Consoles", icon: "🎮", count: 4200 },
      { id: 409, name: "Security Equipment", icon: "📹", count: 1500 },
      { id: 410, name: "Generators", icon: "⚡", count: 2000 },
      { id: 411, name: "Solar Equipment", icon: "☀️", count: 2000 },
  ]},
  { id: 5, name: "Home, Furniture & Appliances", icon: "/jiji/homes.png", totalItems: 68500, subcategories: [
      { id: 501, name: "Furniture", icon: "🪑", count: 12500 },
      { id: 502, name: "Kitchen Appliances", icon: "🍳", count: 14500 },
      { id: 503, name: "Home Decor", icon: "🖼️", count: 6100 },
      { id: 504, name: "Beds & Mattresses", icon: "🛏️", count: 5400 },
      { id: 505, name: "Chairs", icon: "💺", count: 4300 },
      { id: 506, name: "Tables", icon: "🪵", count: 3900 },
      { id: 507, name: "Sofas", icon: "🛋️", count: 5100 },
      { id: 508, name: "Wardrobes", icon: "🚪", count: 2700 },
      { id: 509, name: "Air Conditioners", icon: "❄️", count: 4600 },
      { id: 510, name: "Refrigerators", icon: "🧊", count: 5200 },
      { id: 511, name: "Washing Machines", icon: "🧺", count: 4200 },
  ]},
  { id: 6, name: "Fashion", icon: "/jiji/fashion.png", totalItems: 48500, subcategories: [
      { id: 601, name: "Clothing", icon: "👗", count: 15600 },
      { id: 602, name: "Shoes", icon: "👟", count: 15600 },
      { id: 603, name: "Bags", icon: "👜", count: 6500 },
      { id: 604, name: "Watches", icon: "⌚", count: 5200 },
      { id: 605, name: "Jewelry", icon: "💍", count: 4100 },
      { id: 606, name: "Wedding Wear", icon: "👰", count: 1500 },
  ]},
  { id: 7, name: "Beauty & Personal Care", icon: "/jiji/health.png", totalItems: 38200, subcategories: [
      { id: 701, name: "Makeup", icon: "💋", count: 9000 },
      { id: 702, name: "Hair Care", icon: "💇", count: 7200 },
      { id: 703, name: "Skin Care", icon: "🧴", count: 18500 },
      { id: 704, name: "Fragrances", icon: "🌸", count: 3500 },
  ]},
  { id: 8, name: "Services", icon: "/jiji/services.png", totalItems: 228200, subcategories: [
      { id: 801, name: "Cleaning", icon: "🧹", count: 5000 },
      { id: 802, name: "Logistics", icon: "🚚", count: 5000 },
      { id: 803, name: "Banking & Finance", icon: "🏦", count: 125000 },
      { id: 804, name: "Telecommunications", icon: "🌐", count: 53200 },
      { id: 805, name: "Photography", icon: "📸", count: 5000 },
      { id: 806, name: "Digital Services", icon: "💻", count: 35000 },
  ]},
  { id: 9, name: "Repair & Construction", icon: "/jiji/repair.png", totalItems: 35500, subcategories: [
      { id: 901, name: "Building Materials", icon: "🧱", count: 25500 },
      { id: 902, name: "Industrial/Engineering", icon: "🏗️", count: 10000 },
  ]},
  { id: 10, name: "Commercial Equipment & Tools", icon: "/jiji/equipment.png", totalItems: 21500, subcategories: [
      { id: 1001, name: "Industrial/Manufacturing", icon: "🏭", count: 8000 },
      { id: 1002, name: "Restaurant/Store", icon: "🍳", count: 6000 },
      { id: 1003, name: "Medical/Electrical", icon: "🩺", count: 7500 },
  ]},
  { id: 11, name: "Leisure & Activities", icon: "/jiji/hobbies.png", totalItems: 18200, subcategories: [
      { id: 1101, name: "Books", icon: "📚", count: 4200 },
      { id: 1102, name: "Sports Equipment", icon: "⚽", count: 5100 },
      { id: 1103, name: "Musical Instruments", icon: "🎸", count: 3600 },
      { id: 1104, name: "Art/Camping/Gaming", icon: "🎮", count: 5300 },
  ]},
  { id: 12, name: "Babies & Kids", icon: "/jiji/babies.png", totalItems: 19500, subcategories: [
      { id: 1201, name: "Baby Clothing/Care", icon: "👶", count: 7600 },
      { id: 1202, name: "Toys", icon: "🧸", count: 6100 },
      { id: 1203, name: "Strollers/Car Seats", icon: "🛒", count: 4000 },
      { id: 1204, name: "School Supplies", icon: "🎒", count: 1800 },
  ]},
  { id: 13, name: "Food, Agriculture & Farming", icon: "/jiji/agriculture.png", totalItems: 128500, subcategories: [
      { id: 1301, name: "FMCG Products", icon: "🍞", count: 110000 },
      { id: 1302, name: "Agro-Inputs & Livestock", icon: "🐄", count: 18500 },
  ]},
  { id: 14, name: "Animals & Pets", icon: "/jiji/animals.png", totalItems: 14200, subcategories: [
      { id: 1401, name: "Pets (Dogs/Cats/Birds)", icon: "🐕", count: 9100 },
      { id: 1402, name: "Pet Accessories/Services", icon: "🦴", count: 5100 },
  ]},
  { id: 15, name: "Jobs", icon: "/jiji/jobs.png", totalItems: 36500, subcategories: [
      { id: 1501, name: "General/Admin/Sales", icon: "🏢", count: 15000 },
      { id: 1502, name: "IT/Engineering/Healthcare", icon: "💻", count: 16200 },
      { id: 1503, name: "Marketing/Teaching", icon: "📣", count: 5300 },
  ]},
  { id: 16, name: "Seeking Work - CVs", icon: "/jiji/jobseekers.png", totalItems: 12400, subcategories: [
      { id: 1601, name: "Corporate/Finance CVs", icon: "🧾", count: 3900 },
      { id: 1602, name: "Technical/IT/Eng CVs", icon: "💻", count: 4800 },
      { id: 1603, name: "Vocational/Teaching CVs", icon: "📚", count: 3700 },
  ]},
];



// export const categories = [
//   {
//     id: 1,
//     name: "Vehicles",
//     icon: "/jiji/car.png",
//     totalItems: 40230,
//     subcategories: [
//       { id: 101, name: "Cars", icon: "🚙", count: 12450 },
//       { id: 102, name: "Buses & Microbuses", icon: "🚌", count: 820 },
//       { id: 103, name: "Trucks & Trailers", icon: "🚛", count: 640 },
//       { id: 104, name: "Motorcycles & Scooters", icon: "🏍️", count: 3100 },
//       { id: 105, name: "Heavy Equipment", icon: "🏗️", count: 540 },
//       { id: 106, name: "Watercraft & Boats", icon: "🚤", count: 120 },
//       { id: 107, name: "Vehicle Parts", icon: "🔧", count: 9800 },
//       { id: 108, name: "Vehicle Accessories", icon: "🛞", count: 6700 },
//       { id: 109, name: "Auto Repair Services", icon: "🧰", count: 2300 },
//       { id: 110, name: "Vehicle Rentals", icon: "🔑", count: 3760 },
//     ],
//   },

//   {
//     id: 2,
//     name: "Property",
//     icon: "/jiji/property.png",
//     totalItems: 55290,
//     subcategories: [
//       { id: 201, name: "Houses & Apartments for Sale", icon: "🏡", count: 14500 },
//       { id: 202, name: "Houses & Apartments for Rent", icon: "🏢", count: 18300 },
//       { id: 203, name: "Land & Plots", icon: "🌍", count: 7600 },
//       { id: 204, name: "Commercial Property", icon: "🏬", count: 4100 },
//       { id: 205, name: "Short Let", icon: "🛏️", count: 3400 },
//       { id: 206, name: "Event Centers", icon: "🎪", count: 890 },
//       { id: 207, name: "Property Services", icon: "🧑‍🔧", count: 6500 },
//     ],
//   },

//   {
//     id: 3,
//     name: "Phones & Tablets",
//     icon: "/jiji/phones.png",
//     totalItems: 49800,
//     subcategories: [
//       { id: 301, name: "Smartphones", icon: "📱", count: 22000 },
//       { id: 302, name: "Tablets", icon: "📲", count: 3400 },
//       { id: 303, name: "Smart Watches", icon: "⌚", count: 4100 },
//       { id: 304, name: "Accessories", icon: "🔌", count: 15000 },
//       { id: 305, name: "Mobile Phones", icon: "☎️", count: 5300 },
//     ],
//   },

//   {
//     id: 4,
//     name: "Electronics",
//     icon: "/jiji/electronics.png",
//     totalItems: 63500,
//     subcategories: [
//       { id: 401, name: "TVs", icon: "📺", count: 8900 },
//       { id: 402, name: "Audio & Music Equipment", icon: "🎧", count: 4200 },
//       { id: 403, name: "Computer Hardware", icon: "🖥️", count: 7600 },
//       { id: 404, name: "Computer Accessories", icon: "🖱️", count: 12000 },
//       { id: 405, name: "Cameras", icon: "📷", count: 3100 },
//       { id: 406, name: "Printers", icon: "🖨️", count: 1800 },
//       { id: 407, name: "Networking Equipment", icon: "📡", count: 2200 },
//       { id: 408, name: "Video Game Consoles", icon: "🎮", count: 2600 },
//       { id: 409, name: "Security Equipment", icon: "📹", count: 1500 },
//       { id: 410, name: "Generators", icon: "⚡", count: 5400 },
//       { id: 411, name: "Solar Equipment", icon: "☀️", count: 8200 },
//     ],
//   },

//   {
//     id: 5,
//     name: "Home, Furniture & Appliances",
//     icon: "/jiji/homes.png",
//     totalItems: 62200,
//     subcategories: [
//       { id: 501, name: "Furniture", icon: "🪑", count: 12500 },
//       { id: 502, name: "Kitchen Appliances", icon: "🍳", count: 8200 },
//       { id: 503, name: "Home Decor", icon: "🖼️", count: 6100 },
//       { id: 504, name: "Beds & Mattresses", icon: "🛏️", count: 5400 },
//       { id: 505, name: "Chairs", icon: "💺", count: 4300 },
//       { id: 506, name: "Tables", icon: "🪵", count: 3900 },
//       { id: 507, name: "Sofas", icon: "🛋️", count: 5100 },
//       { id: 508, name: "Wardrobes", icon: "🚪", count: 2700 },
//       { id: 509, name: "Air Conditioners", icon: "❄️", count: 4600 },
//       { id: 510, name: "Refrigerators", icon: "🧊", count: 5200 },
//       { id: 511, name: "Washing Machines", icon: "🧺", count: 4200 },
//     ],
//   },

//   {
//     id: 6,
//     name: "Fashion",
//     icon: "/jiji/fashion.png",
//     totalItems: 45800,
//     subcategories: [
//       { id: 601, name: "Clothing", icon: "👗", count: 15000 },
//       { id: 602, name: "Shoes", icon: "👟", count: 12000 },
//       { id: 603, name: "Bags", icon: "👜", count: 6500 },
//       { id: 604, name: "Watches", icon: "⌚", count: 5200 },
//       { id: 605, name: "Jewelry", icon: "💍", count: 4100 },
//       { id: 606, name: "Wedding Wear", icon: "👰", count: 1800 },
//       { id: 607, name: "Luggage", icon: "🧳", count: 1200 },
//       { id: 608, name: "Underwear", icon: "🩲", count: 1000 },
//       { id: 609, name: "Traditional Wear", icon: "👘", count: 3000 },
//     ],
//   },

//   {
//     id: 7,
//     name: "Beauty & Personal Care",
//     icon: "/jiji/health.png",
//     totalItems: 29800,
//     subcategories: [
//       { id: 701, name: "Makeup", icon: "💋", count: 9000 },
//       { id: 702, name: "Hair Care", icon: "💇", count: 7200 },
//       { id: 703, name: "Skin Care", icon: "🧴", count: 6100 },
//       { id: 704, name: "Fragrances", icon: "🌸", count: 4200 },
//       { id: 705, name: "Vitamins & Supplements", icon: "💊", count: 1800 },
//       { id: 706, name: "Barber Equipment", icon: "✂️", count: 900 },
//       { id: 707, name: "Salon Equipment", icon: "💈", count: 600 },
//     ],
//   },

//   {
//     id: 8,
//     name: "Services",
//     icon: "/jiji/services.png",
//     totalItems: 38500,
//     subcategories: [
//       { id: 801, name: "Cleaning", icon: "🧹", count: 5200 },
//       { id: 802, name: "Logistics", icon: "🚚", count: 4100 },
//       { id: 803, name: "Catering", icon: "🍽️", count: 3800 },
//       { id: 804, name: "Event Planning", icon: "🎉", count: 4600 },
//       { id: 805, name: "Photography", icon: "📸", count: 3900 },
//       { id: 806, name: "Graphic Design", icon: "🎨", count: 4200 },
//       { id: 807, name: "Web Development", icon: "💻", count: 5100 },
//       { id: 808, name: "Digital Marketing", icon: "📢", count: 4400 },
//       { id: 809, name: "Legal Services", icon: "⚖️", count: 1500 },
//       { id: 810, name: "Security Services", icon: "🛡️", count: 1700 },
//     ],
//   },

//   {
//     id: 9,
//     name: "Repair & Construction",
//     icon: "/jiji/repair.png",
//     totalItems: 28900,
//     subcategories: [
//       { id: 901, name: "Building Materials", icon: "🧱", count: 8200 },
//       { id: 902, name: "Electrical Services", icon: "💡", count: 3100 },
//       { id: 903, name: "Plumbing", icon: "🚿", count: 2900 },
//       { id: 904, name: "Painting", icon: "🎨", count: 2100 },
//       { id: 905, name: "Roofing", icon: "🏠", count: 1800 },
//       { id: 906, name: "Interior Design", icon: "🪞", count: 4200 },
//       { id: 907, name: "Architecture", icon: "📐", count: 2600 },
//       { id: 908, name: "Engineering Services", icon: "🧑‍🔬", count: 4000 },
//     ],
//   },

//   {
//     id: 10,
//     name: "Commercial Equipment & Tools",
//     icon: "/jiji/equipment.png",
//     totalItems: 21500,
//     subcategories: [
//       { id: 1001, name: "Manufacturing Equipment", icon: "🏭", count: 4200 },
//       { id: 1002, name: "Restaurant Equipment", icon: "🍳", count: 3100 },
//       { id: 1003, name: "Store Equipment", icon: "🏪", count: 2600 },
//       { id: 1004, name: "Printing Equipment", icon: "🖨️", count: 1900 },
//       { id: 1005, name: "Medical Equipment", icon: "🩺", count: 3200 },
//       { id: 1006, name: "Industrial Machinery", icon: "🏗️", count: 2400 },
//       { id: 1007, name: "Electrical Equipment", icon: "⚡", count: 2100 },
//       { id: 1008, name: "Generators", icon: "🔋", count: 2000 },
//     ],
//   },

//   {
//     id: 11,
//     name: "Leisure & Activities",
//     icon: "/jiji/hobbies.png",
//     totalItems: 18200,
//     subcategories: [
//       { id: 1101, name: "Books", icon: "📚", count: 4200 },
//       { id: 1102, name: "Sports Equipment", icon: "⚽", count: 5100 },
//       { id: 1103, name: "Musical Instruments", icon: "🎸", count: 3600 },
//       { id: 1104, name: "Art Supplies", icon: "🖌️", count: 1900 },
//       { id: 1105, name: "Camping Equipment", icon: "⛺", count: 1800 },
//       { id: 1106, name: "Gaming", icon: "🎮", count: 1600 },
//     ],
//   },

//   {
//     id: 12,
//     name: "Babies & Kids",
//     icon: "/jiji/babies.png",
//     totalItems: 19500,
//     subcategories: [
//       { id: 1201, name: "Baby Clothing", icon: "👶", count: 5200 },
//       { id: 1202, name: "Toys", icon: "🧸", count: 6100 },
//       { id: 1203, name: "Strollers", icon: "🛒", count: 2200 },
//       { id: 1204, name: "Car Seats", icon: "🚗", count: 1800 },
//       { id: 1205, name: "Baby Care", icon: "🍼", count: 2400 },
//       { id: 1206, name: "School Supplies", icon: "🎒", count: 1800 },
//     ],
//   },

//   {
//     id: 13,
//     name: "Food, Agriculture & Farming",
//     icon: "/jiji/agriculture.png",
//     totalItems: 24300,
//     subcategories: [
//       { id: 1301, name: "Livestock", icon: "🐄", count: 5200 },
//       { id: 1302, name: "Poultry", icon: "🐓", count: 6100 },
//       { id: 1303, name: "Seeds", icon: "🌱", count: 3100 },
//       { id: 1304, name: "Fertilizers", icon: "🧪", count: 2400 },
//       { id: 1305, name: "Farm Machinery", icon: "🚜", count: 3900 },
//       { id: 1306, name: "Animal Feed", icon: "🌾", count: 2200 },
//       { id: 1307, name: "Food Products", icon: "🍞", count: 1400 },
//     ],
//   },

//   {
//     id: 14,
//     name: "Animals & Pets",
//     icon: "/jiji/animals.png",
//     totalItems: 14200,
//     subcategories: [
//       { id: 1401, name: "Dogs", icon: "🐕", count: 5200 },
//       { id: 1402, name: "Cats", icon: "🐈", count: 2100 },
//       { id: 1403, name: "Birds", icon: "🐦", count: 1800 },
//       { id: 1404, name: "Fish", icon: "🐟", count: 1600 },
//       { id: 1405, name: "Pet Accessories", icon: "🦴", count: 2400 },
//       { id: 1406, name: "Veterinary Services", icon: "🏥", count: 1100 },
//     ],
//   },

//   {
//     id: 15,
//     name: "Jobs",
//     icon: "/jiji/jobs.png",
//     totalItems: 36500,
//     subcategories: [
//       { id: 1501, name: "Accounting", icon: "🧾", count: 4200 },
//       { id: 1502, name: "Administration", icon: "🏢", count: 3600 },
//       { id: 1503, name: "Customer Service", icon: "🎧", count: 4800 },
//       { id: 1504, name: "Engineering", icon: "🧑‍🔧", count: 5200 },
//       { id: 1505, name: "Healthcare", icon: "🏥", count: 4100 },
//       { id: 1506, name: "IT & Software", icon: "💻", count: 6900 },
//       { id: 1507, name: "Marketing", icon: "📣", count: 3900 },
//       { id: 1508, name: "Sales", icon: "💰", count: 3600 },
//       { id: 1509, name: "Security", icon: "🛡️", count: 2200 },
//       { id: 1510, name: "Teaching", icon: "📚", count: 2000 },
//     ],
//   },

//   {
//     id: 16,
//     name: "Seeking Work - CVs",
//     icon: "/jiji/jobseekers.png",
//     totalItems: 12400,
//     subcategories: [
//       { id: 1601, name: "Accounting CVs", icon: "🧾", count: 2100 },
//       { id: 1602, name: "Driver CVs", icon: "🚗", count: 1800 },
//       { id: 1603, name: "Engineering CVs", icon: "🧑‍🔧", count: 2200 },
//       { id: 1604, name: "IT CVs", icon: "💻", count: 2600 },
//       { id: 1605, name: "Marketing CVs", icon: "📣", count: 1900 },
//       { id: 1606, name: "Teaching CVs", icon: "📚", count: 1800 },
//     ],
//   },
// ];